version: "3"

services:
  react:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - node_modules:/workspace/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node_modules: